# yamllint disable-file
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ui-mask"
  description: "Apply a mask on an input field so the user can only type pre-determined pattern."
  title: "ui-mask"
  tags:
    - emr
  links:
    - url: https://fortify.philips.com/ssc/html/ssc/version/18129/audit?filterset=69608e28-5b92-4f48-98c2-d9c6d91fa347&orderby=friority&viewTab=code
      title: Fortify
      icon: docs
    - url: https://blackduck.philips.com/api/projects/28c5134a-5571-4796-9495-380f58af0010/versions/91f15213-cbb1-4d30-b168-ff78185d47c2/components?filter=bomInclusion%3Afalse&filter=bomMatchInclusion%3Afalse&filter=bomMatchReviewStatus%3Areviewed&limit=100&offset=0
      title: BlackDuck
      icon: docs      
  annotations:
    blackduck/project: EMR-CM-TasyFrameworkDependencies/ui-mask
    fortify/project: EMR/ui-mask
spec:
  type: "library"
  owner: "group:default/emr-eisenbahn-contributors"
  lifecycle: "production"
